// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6utYhJBRdruHSe7Xbk8bSJlPazUJYWs',
    appId: '1:965853850603:web:726de32df54297e8e247ae',
    messagingSenderId: '965853850603',
    projectId: 'instagram-tut-2727d',
    authDomain: 'instagram-tut-2727d.firebaseapp.com',
    storageBucket: 'instagram-tut-2727d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYhFWZnG9H_qpFD0rJ0RdB52IpXZwEr0',
    appId: '1:965853850603:android:2c1b981eeff212f8e247ae',
    messagingSenderId: '965853850603',
    projectId: 'instagram-tut-2727d',
    storageBucket: 'instagram-tut-2727d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOTqpE5xe_GxJRDHIs-myQGNXX0P0hMrM',
    appId: '1:965853850603:ios:bce83a2216e136c7e247ae',
    messagingSenderId: '965853850603',
    projectId: 'instagram-tut-2727d',
    storageBucket: 'instagram-tut-2727d.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOTqpE5xe_GxJRDHIs-myQGNXX0P0hMrM',
    appId: '1:965853850603:ios:091207070fb5ac7be247ae',
    messagingSenderId: '965853850603',
    projectId: 'instagram-tut-2727d',
    storageBucket: 'instagram-tut-2727d.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
